export enum AuditAction {
  CREATE_LOG = 'CREATE_LOG',
  SEARCH_LOGS = 'SEARCH_LOGS',
  VIEW_LOG = 'VIEW_LOG',
  EXPORT_DATA = 'EXPORT_DATA',
  REVIEW_EMERGENCY_ACCESS = 'REVIEW_EMERGENCY_ACCESS',
  INVESTIGATE_ALERT = 'INVESTIGATE_ALERT',
  RESOLVE_ALERT = 'RESOLVE_ALERT',
  GENERATE_REPORT = 'GENERATE_REPORT',
  ACCESS_STATISTICS = 'ACCESS_STATISTICS',
  FAILED_LOGIN_ATTEMPT = 'FAILED_LOGIN_ATTEMPT',
  ACCESS_GRANTED = 'ACCESS_GRANTED',
  VIEW_MEDICAL_RECORD = 'VIEW_MEDICAL_RECORD',
  EMERGENCY_ACCESS = 'EMERGENCY_ACCESS',
  DATABASE_LATENCY = 'DATABASE_LATENCY',
  QUERY_SLOW = 'QUERY_SLOW',
  INDEX_MISSING = 'INDEX_MISSING',
  MAPPING_MISMATCH = 'MAPPING_MISMATCH',
  KAFKA_CONNECTION_ISSUE = 'KAFKA_CONNECTION_ISSUE',
  CANNOT_CONNECT_TO_ELASTICSEARCH = 'CANNOT_CONNECT_TO_ELASTICSEARCH',
  
  // etc.
}
