export enum AuditAction {
  CREATE_LOG = 'CREATE_LOG',
  SEARCH_LOGS = 'SEARCH_LOGS',
  VIEW_LOG = 'VIEW_LOG',
  EXPORT_DATA = 'EXPORT_DATA',
  REVIEW_EMERGENCY_ACCESS = 'REVIEW_EMERGENCY_ACCESS',
  INVESTIGATE_ALERT = 'INVESTIGATE_ALERT',
  RESOLVE_ALERT = 'RESOLVE_ALERT',
  GENERATE_REPORT = 'GENERATE_REPORT',
  ACCESS_STATISTICS = 'ACCESS_STATISTICS',
  // etc.
}
